### ISSUE TITLE
Travis CI fails with "Permission denied: /data/grassdata"

### ISSUE THREAD

**Issue by wenzeslaus** [wenzeslaus/forestfrag3d#1]
First error in the output:

```
...
travis_time:end:0750f873:start=1499388353704044843,finish=1499389053330749594,duration=699626704751
[0Ktravis_fold:end:install.1
[0Ktravis_fold:start:install.2
[0Ktravis_time:start:0b9edaa8
[0K$ mkdir ffdata

travis_time:end:0b9edaa8:start=1499389053335485732,finish=1499389053340186311,duration=4700579
[0Ktravis_fold:end:install.2
[0Ktravis_time:start:00ac54d8
[0K$ docker run --rm -v $(pwd)/ffdata:/data -it forestfrag3d /code/run.sh test
Default locale not found, using UTF-8
WARNING: Default locale settings are missing. GRASS running with C locale.
WARNING: Searched for a web browser, but none found
Creating new GRASS GIS location/mapset...
Traceback (most recent call last):
  File "/usr/local/bin/grass", line 1987, in <module>
    main()
  File "/usr/local/bin/grass", line 1901, in main
    geofile=params.geofile, create_new=True)
  File "/usr/local/bin/grass", line 925, in set_mapset
    create_location(gisdbase, location_name, geofile)
  File "/usr/local/bin/grass", line 794, in create_location
    epsg=epsg, datum_trans=datum_trans)
  File "/usr/local/grass-7.3.svn/etc/python/grass/script/core.py", line 1406, in create_location
    os.mkdir(dbase)
OSError: [Errno 13] Permission denied: '/data/grassdata'

7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=C,Utf16=off,HugeFiles=on,2 CPUs)

Processing archive: /code/points.las.7z

can not open output file points.las
Skipping    points.las

Sub items Errors: 1
...
```

**Comment by wenzeslaus** [comment]
Fixed in 1f13d42c.
